spring.application.name=Application
server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
app.required-db-tag=version_1.07
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
#logging.level.org.springframework.security=DEBUG

server.servlet.session.timeout=1m
# pt a schimba modul in care spring interpreteaza parametrul page
# in loc sa indexeze prima pagina de la 0 o face de la 1
spring.data.web.pageable.one-indexed-parameters=true

spring.ai.ollama.base-url=https://software-ai.digi.ro:8004
OLLAMA_KEY=${OLLAMA_KEY}

spring.ai.ollama.embedding.options.model=nomic-embed-text:latest
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.dimensions=768

spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.index-type=HNSW

spring.ai.mcp.server.name=documents-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC